### ISSUE TITLE
The reload, peunload, perun commands do not have any output

### ISSUE THREAD

**Issue by woOzZ2** [Octoberfest7/Inline-Execute-PE#3] opened 2023-03-24 02:54 UTC
Cobalt Strike 4.5
script console: "Successfully located /Applications/CobaltStrike.app/petable.txt!"
execute `peload C:\windows\system32\windowspowershell\v1.0\powershell.exe —local` The Beacon console doesn't have any output, but the script console has error output:
<img width="675" alt="image" src="https://user-images.githubusercontent.com/21095700/227405792-29afc350-5a96-4ed9-ba90-6898f6f1d5d0.png">
<img width="897" alt="image" src="https://user-images.githubusercontent.com/21095700/227406008-8a4b69cb-3aee-42c6-899d-99590a27fea6.png">
The Event log also has output:
<img width="1130" alt="image" src="https://user-images.githubusercontent.com/21095700/227406219-7fff7f10-7f8c-4a0d-9e6b-3d0bd1258a5f.png">
Then execute 'petable' in the beacon console, without any successfully loaded pe files:
<img width="1030" alt="image" src="https://user-images.githubusercontent.com/21095700/227406417-5780b173-fb51-4d74-a167-5294e65013b3.png">
From a session to the new spawn and then exit the previous beacon, the first 'petable' is the output of the previous beacon that has not exited, and the second 'petable' is the output of the previous beacon that has exited:
<img width="1059" alt="image" src="https://user-images.githubusercontent.com/21095700/227407217-4a13c196-a450-4060-a2bf-b808977563f0.png">
As soon as I execute the perun script console it outputs：
```
[10:42:43] Function call &beacon_inline_execute failed: can't run BOF: linker errors for UserSpecifiedFull:

Unknown symbol '.bss'
Unknown symbol '.bss'
Unknown symbol '.bss'
Unknown symbol '.bss'
Unknown symbol '.bss'
.....
 at Inline-Execute-PE.cna:633
```

Whether you use the O file inside the repo or the O file generated by make, the same result is the above. I get the same output directly from `inline-execute reload.o`:
<img width="757" alt="image" src="https://user-images.githubusercontent.com/21095700/227412080-421f2cca-6e18-4970-895b-3502cf445d06.png">

The compiler I used when compiling myself was mingw.

**Comment by Octoberfest7** [comment] 2023-03-24 02:57
If you look at this issue: https://github.com/Octoberfest7/Inline-Execute-PE/issues/1, the bss errors appear to be resolved by updating to latest CS. The follow on errors are all a result of that first one

**Comment by woOzZ2** [comment] 2023-03-24 11:22
> If you look at this issue: #1, the bss errors appear to be resolved by updating to latest CS. The follow on errors are all a result of that first one

Yes, I gave more detailed information because I saw this issue, I am now using CobaltStrike 4.5, and I see that #1 still has problems after using CobaltStrike 4.7.

**Comment by Octoberfest7** [comment] 2023-03-24 11:34
The .bss issue that you are having, the same one as in issue 1, was resolved by the user in issue 1 updating to 4.7. The continued issues that user was having was at that point due to their profile not being configured properly to handle large task sizes, as stated by cobaltstrike in the console.

The "issue" or "bug" with Inline-execute-pe in both of these cases is that it doesn't detect when the BOF fails to run for whatever reason, either due to the bss errors or due to the command not actually going through because of the task size error. So because it assumes that provided none of the input validation checks were tripped when using peload that peload was successful, it populates petable and such even though no pe was actually loaded. 

With an up to date version of cobaltstrike and a profile allowing large task sizes, these issues are resolved. In issue 1, where even after 4.7 his beacons were crashing, it was because peload wasn't actually loading a pe in memory due to the max task size issue, but petable was creating the entry, so when he went and ran peunload afterwards the BOF was trying to reference and free memory that wasn't actually allocated at all.

**Comment by woOzZ2** [comment] 2023-03-24 12:00
> The .bss issue that you are having, the same one as in issue 1, was resolved by the user in issue 1 updating to 4.7. The continued issues that user was having was at that point due to their profile not being configured properly to handle large task sizes, as stated by cobaltstrike in the console.
> 
> The "issue" or "bug" with Inline-execute-pe in both of these cases is that it doesn't detect when the BOF fails to run for whatever reason, either due to the bss errors or due to the command not actually going through because of the task size error. So because it assumes that provided none of the input validation checks were tripped when using peload that peload was successful, it populates petable and such even though no pe was actually loaded.
> 
> With an up to date version of cobaltstrike and a profile allowing large task sizes, these issues are resolved. In issue 1, where even after 4.7 his beacons were crashing, it was because peload wasn't actually loading a pe in memory due to the max task size issue, but petable was creating the entry, so when he went and ran peunload afterwards the BOF was trying to reference and free memory that wasn't actually allocated at all.

Are you talking about the tasks_max_size, tasks_proxy_max_size, tasks_dns_proxy_max_size three parameters in the "profile"? I tried and 4.5 doesn't support these options (an error is reported when starting teamserver), so I'll update to 4.7 to try again. Thank you for your great work.

**Comment by Octoberfest7** [comment] 2023-03-24 12:13
Yes those. They are by default like 1mb so if you want to load like mimikatz which is 1.3mb youd need to increase that field size. 

This works in 4.8 as well so updated to latest works fine too. Let me know how it goes

**Comment by woOzZ2** [comment] 2023-03-25 07:01
> Yes those. They are by default like 1mb so if you want to load like mimikatz which is 1.3mb youd need to increase that field size.
> 
> This works in 4.8 as well so updated to latest works fine too. Let me know how it goes

It works great on Cobaltstrike 4.7! But there are still some problems. 
- peconfig unloadlibraries false is always true 
- During my testing, the target rebooted once, and Windows prompted my PC to restart in 1 minute (this time the Beacon process is lsass.exe) 
- When executing peunload, the beacon will exit 
- There is no safe way to clear the memory area unless the entire process is exited I recommend adding Windows system process recognition, otherwise it is easy to trigger Windows security rules and cause the system to shut down. Finally, do you think it's possible for your tool to work in Cobaltdtrike 4.5? I mean if we modify the 4.5 TS max size

**Comment by Octoberfest7** [comment] 2023-03-25 07:26
Can you provide screenshots of the peconfig unloadlibraries false is always true, as well as executing peunload causes the beacon to exit? The full attack chain, meaning show you using peload, running a command with the PE, and then using peconfig and then peunload and showing the undesirable behavior.

I'm not sure what you are referring to when you say "trigger Windows security rules and cause the system to shut down".  Maybe this is something to do with certain Windows processes, like how you mention LSASS? I can't think of a reason one would run a beacon out of a process like LSASS, as there is no scenario where LSASS should be communicating out via HTTPS or even over a named pipe in the case of an SMB beacon.  I'd file this as a "not going to fix".

**Comment by woOzZ2** [comment] 2023-03-25 08:28
> 



> Can you provide screenshots of the peconfig unloadlibraries false is always true, as well as executing peunload causes the beacon to exit? The full attack chain, meaning show you using peload, running a command with the PE, and then using peconfig and then peunload and showing the undesirable behavior.
> 
> I'm not sure what you are referring to when you say "trigger Windows security rules and cause the system to shut down". Maybe this is something to do with certain Windows processes, like how you mention LSASS? I can't think of a reason one would run a beacon out of a process like LSASS, as there is no scenario where LSASS should be communicating out via HTTPS or even over a named pipe in the case of an SMB beacon. I'd file this as a "not going to fix".

Because once lsass.exe exits, windows will remind "Your PC will automatically restart in one minute", why should I run Beacon in lsass because I usually choose system process instead of new process injection, but obviously I ignore the network The characteristics of traffic, thank you for your reminder. 
- For peconfig unloadlibraries false is always True, I think it should be that I execute peconfig unloadlibraries false before peload, so it is my operation problem. 
- I just tried to peload a program written in Golang, but I found that during the loading phase, Beacon has a little error: 
<img width="623" alt="image" src="https://user-images.githubusercontent.com/21095700/227706236-2b901a4f-6fa7-4dab-b78a-0eda98e3ab53.png">

- There is no error when I try again, but when I perun the program written in Golang, I get an error, A lot of hexadecimal data is output: 
```
beacon> perun
[+] host called home, sent: 6900 bytes
[+] received output:
Exception 0xc0000005 0x0 0xe73460 0x2f3562c9
PC=0x2f3562c9

runtime: unknown pc 0x2f3562c9
stack: frame={sp:0x2b6f798, fp:0x0} stack=[0x0,0x2b6f8f0)
0x0000000002b6f698:  0x0000000000000000  0x0000000000000000 
0x0000000002b6f6a8:  0x0000000000000000  0x000005b8fffffb30 
0x0000000002b6f6b8:  0x000004d0fffffb30  0x00000000000000e8 
0x0000000002b6f6c8:  0x00000000301d2720  0x00000000c0000005 
0x0000000002b6f6d8:  0x0000000000000000  0x000000002f3562c9 
...
[+] received output:
perun complete
```
- Is it possible that cobaltstrike4.5 can be retrofitted to support your tool? 

The strange thing is that I didn't do anything, and now I find that beacon doesn't exit very often. When I first started to experience your project, Beacon would often quit due to peload and peunload, I think I am familiar with this useful tool now, thank you for your contribution.

**Comment by Octoberfest7** [comment] 2023-03-25 15:54
From the introduction:

"Inline-Execute-PE was designed around x64 Beacons and x64 Windows C or C++ executables compiled using Mingw or Visual Studio. This project does not support x86 executables or x64 executables written in a different language or compiled using a different compiler."

Golang binaries are not supported. I also do not consider undefined or undesirable behavior that comes from using this tool in critical system processes to be within the scope of this project. I will not be creating a workaround for this project to work with 4.5 or earlier CS, as users with legitimate licenses can upgrade their CS version at any time.

**Closed as completed by Octoberfest7** 2023-03-25 15:54 UTC
